AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for PDF storage with proper permissions'

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: 'arc-prime-pdf-storage-bucket'
  
  Environment:
    Type: String
    Description: Environment name
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']

Resources:
  # S3 Bucket for PDF storage
  PDFStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: ['GET', 'PUT', 'POST', 'DELETE', 'HEAD']
            AllowedOrigins: ['*']
            MaxAge: 3600
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90

  # IAM Role for Lambda functions to access S3
  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'PDFStorageS3AccessRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3PDFBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                Resource: !Sub '${PDFStorageBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !GetAtt PDFStorageBucket.Arn

  # Bucket Policy for additional security
  PDFStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PDFStorageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt PDFStorageBucket.Arn
              - !Sub '${PDFStorageBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

Outputs:
  BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref PDFStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: 'ARN of the S3 bucket'
    Value: !GetAtt PDFStorageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  
  S3AccessRoleArn:
    Description: 'ARN of the IAM role for S3 access'
    Value: !GetAtt S3AccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3AccessRoleArn'
